apiVersion: apps/v1
kind: Deployment
metadata:
  name: rocketchat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketchat-server
  template:
    metadata:
      labels:
        app: rocketchat-server
    spec:
      containers:
        - name: rocketchat-server
          image: rocketchat/rocket.chat:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL # the application expects to find the MongoDB connection details in this environment variable
              valueFrom:
                secretKeyRef:
                  name: mongosecret # the name of the Kubernetes secret containing the data
                  key: MONGOCONNECTION # the key inside the Kubernetes secret containing the data       
#            - name: MONGO_OPLOG_URL # the application expects to find the MongoDB connection details in this environment variable
#              valueFrom:
#                secretKeyRef:
#                  name: mongosecret # the name of the Kubernetes secret containing the data
#                  key: MONGOCONNECTION # the key inside the Kubernetes secret containing the data                          
#          imagePullPolicy: Always